apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomize-transformers.yaml

resources:
  - rollout.yaml
  - services.yaml
  - ingress.yaml

configMapGenerator:
- name: app-index-html
  files:
  - index.html