apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - services.yaml
  - ingress.yaml

configMapGenerator:
- name: app-index-html
  files:
  - index.html

patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        checksum/config: $(cat index.html | sha256sum)
  target:
    kind: Rollout
    name: app