apiVersion: v1
kind: Service
metadata:
  name: app-stable
  namespace: app-demo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app
    rollouts-pod-template-hash: stable
---
apiVersion: v1
kind: Service
metadata:
  name: app-canary
  namespace: app-demo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app
    rollouts-pod-template-hash: canary
