# Settings generales de la aplicación
nameOverride: app # Nombre base para los recursos
namespace: app-demo
replicas: 5

image:
  repository: fpultera/app-demo
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

# Labels que se usarán en todos los recursos
labels:
  app: nginx

# Definición de los Services para la estrategia canary
service:
  stable:
    name: app-stable
    type: ClusterIP
    port: 80
  canary:
    name: app-canary
    type: ClusterIP
    port: 80

# Configuración del Ingress
ingress:
  enabled: true
  className: nginx
  name: app-ingress
  host: app-demo.local
  annotations:
    # Estas anotaciones son cruciales para que Argo Rollouts controle el tráfico
    # # a través del Ingress Controller de Nginx.
    # nginx.ingress.kubernetes.io/canary: "true"
    # nginx.ingress.kubernetes.io/canary-weight: "0"
    # argocd.argoproj.io/managed-by-rollouts-ingress: "true"
    # argocd.argoproj.io/sync-wave: "0"

# Estrategia y pasos del Rollout
rollout:
  strategy:
    steps:
      - setWeight: 20
      - pause: { duration: 10s }
      - setWeight: 50
      - pause: { duration: 30s }
      - setWeight: 100
